services:
  - type: web
    runtime: node
    name: web-app
    plan: free
    buildCommand: |
      pnpm install
      pnpm turbo db:generate
      pnpm turbo build
    startCommand: pnpm turbo start --filter=@profile/platform-web -- --port 3000
    autoDeploy: true
    region: virginia

  - type: web
    runtime: node
    name: api-app
    plan: free
    buildCommand: |
      pnpm install
      pnpm turbo db:generate
      pnpm turbo build
    startCommand: pnpm turbo start --filter=@profile/platform-api -- --port 3001
    autoDeploy: true
    region: virginia
