envVarGroups:
  - name: shared-env
    envVars:
      - key: DATABASE_URL
        sync: false

services:
  - type: web
    runtime: node
    name: profile-app
    plan: free
    buildCommand: |
      pnpm install
      pnpm turbo db:generate
      pnpm turbo build
    startCommand: |
      pnpm turbo start --filter=@profile/platform-web -- --port $PORT &
      pnpm turbo start --filter=@profile/platform-api -- --port $API_PORT
    autoDeploy: true
    region: virginia
    envVars:
      - key: NODE_ENV
        sync: false
      - key: NEXT_PUBLIC_API_PORT
        sync: false
      - key: API_URL
        sync: false
      - key: WEB_APP_URL
        sync: false
      - key: PORT
        sync: false
      - key: API_PORT
        sync: false
      - key: LOG_LEVEL
        sync: false
      - key: JWT_SECRET
        sync: false
