export const SUPPORTED_PLATFORMS = [
  "instagram",
  "facebook",
  "twitter",
  "linkedin",
  "youtube",
  "tiktok",
  "whatsapp",
  "telegram",
  "discord",
  "twitch",
  "spotify",
  "soundcloud",
  "github",
] as const;

export const TRUSTED_DOMAINS = [
  "instagram.com",
  "facebook.com",
  "twitter.com",
  "linkedin.com",
  "youtube.com",
  "tiktok.com",
  "whatsapp.com",
  "telegram.org",
  "discord.com",
  "twitch.tv",
  "spotify.com",
  "soundcloud.com",
  "github.com",
] as const;
